[package]
name = "create-rust-snake-game"
version = "0.1.0"
edition = "2021"

[dependencies]
ggez = "=0.9.3"
rand = "=0.8.5"

[dev-dependencies]
proptest = "1.4.0"
criterion = "0.5.1"

[[bench]]
name = "snake_performance"
harness = false
